"""
Django settings for OAuth20Server project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import base64
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%xw4t*tob&t#@!$r45ra56ftc%qe(d+#1vvw+$&t-(1_z916)&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'oauth2_provider',
    'sslserver',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OAuth20Server.urls'
CORS_ORIGIN_ALLOW_ALL = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OAuth20Server.wsgi.application'
LOGIN_URL = '/admin/login/'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'OAuth20Db',
        'USER': 'a2',
        'PASSWORD': '32167',
        'HOST': 'localhost',
        # 'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OAUTH2_PROVIDER = {
    "ACCESS_TOKEN_EXPIRE_SECONDS": 10800,
    "OAUTH2_VALIDATOR_CLASS": "OAuth20Server.oauth2_validators.CustomOAuth2Validator",
    "OIDC_ENABLED": True,
    "PKCE_REQUIRED": False,
    "OIDC_RSA_PRIVATE_KEY": """-----BEGIN RSA PRIVATE KEY-----
MIICXQIBAAKBgQDQ9hvsUOjRzLiRydUut2LxMvHjaAx3wX0BrvtGpKX1rq3Quaa+
oLszkhzJCkZLx1iUAOpNH40tTxGZB0j7cEKS/QT3lhKeUOrNSkDpeUUljr+tlWTS
kZVnWC/cLiEbkTkx09r8BqkUmfEQR2GtzO5gCyTz0++PSxUEtl+ovuOMHQIDAQAB
AoGBAKagCUYYgn6BU5AVNGQrIb+Z0x514rM/29GS2ZXMRvYw0zNERv1tJ7mIwmFh
Swq0LCLg0/SpuyatDShMkdrF+p7QK8ywyvdF6ssCGDS7icebAovAGbnqmc3170xL
mLGvm5i/JBVcu5KYZmNyp66pxS+lt8lh2zhpiMHxL97hQHRVAkEA67895cqe99mI
OSpJ7FtDE2BPteOM5j0KwoiW709wYusXDXuPryOU5qreMd8CysCuDHIB1aoB5mk1
fogyrz6bywJBAOLpxd+ksd76Nkr62n4aNt9aknKJVJRMWiz7afimgUpyVV6ICmOJ
yxnSvUyhNG3MXIX0SwxNrsxsnntA1hgcyrcCQQDakhL3bGb68IqmRZkINIz59/+v
aewGw22ocy9NbV+Ltt9Gttq+zMSPILilkFhsVzyHeWRODzN3xu+8AtbLN8cFAkAK
ZcHeZJKN8BMqzmHSo2reQy0wuGA6x2DebMrHTQHhommNAljPhNHcpg5sg3p+iX23
2aDSuICI93UvmqH0yuTzAkByfnW4xgjbbmhBwXvGRUT50/EFuAeD5FfdX6JbX6Zf
5oQrwnl3jv9eIW2hyNiJJq3UYd3iBUUoVof1dzeDW6As
-----END RSA PRIVATE KEY-----
""",
    # this is the list of available scopes
    'SCOPES': {
        'read': 'Read scope',
        'write': 'Write scope',
        'openid': "OpenID Connect scope",
    },
}
pass
